#!/bin/bash

# ============================================
# SETUP.SH
# Eerste keer configuratie - personaliseert de
# cloud-init configs met jouw instellingen
#
# Gebruik:
#   bash setup.sh
#   bash setup.sh --ssh-key "ssh-ed25519 AAAA..."
#   bash setup.sh --ssh-key "key1" --ssh-key "key2"
# ============================================

set -e

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
# shellcheck disable=SC2034
BOLD='\033[1m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── Argument parsing ──────────────────────────
SSH_KEY_ARGS=()
while [[ $# -gt 0 ]]; do
    case $1 in
        --ssh-key) SSH_KEY_ARGS+=("$2"); shift 2 ;;
        *)         shift ;;
    esac
done

# ── Header ────────────────────────────────────
clear 2>/dev/null || true
echo ""
echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Proxmox Templates - Setup Wizard      ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""

# ── Step 0: Language / Taal ─────────────────────
echo -e "${BOLD}Select language / Kies taal${NC}"
echo -e "─────────────────────────────────────────"
echo ""
echo "  [1] English"
echo "  [2] Nederlands"
echo ""
read -rp "  Choice / Keuze [1]: " LANG_INPUT
case ${LANG_INPUT:-1} in
    2) LANG_CHOICE="nl" ;;
    *) LANG_CHOICE="en" ;;
esac

# Preserve any existing storage config so we only overwrite what's new
EXISTING_VM_STORAGE=""
EXISTING_LXC_STORAGE=""
EXISTING_LXC_TEMPLATE_STORAGE=""
if [[ -f "$SCRIPT_DIR/lib/config.sh" ]]; then
    # shellcheck disable=SC1091
    source "$SCRIPT_DIR/lib/config.sh"
    EXISTING_VM_STORAGE="${VM_STORAGE:-${STORAGE:-}}"
    EXISTING_LXC_STORAGE="${LXC_STORAGE:-}"
    EXISTING_LXC_TEMPLATE_STORAGE="${LXC_TEMPLATE_STORAGE:-}"
fi

# Save language choice (storage comes later in step 4)
cat > "$SCRIPT_DIR/lib/config.sh" << EOF
#!/bin/bash
# Generated by setup.sh — do not edit manually
LANG_CHOICE="$LANG_CHOICE"
EOF

# Load language strings
source "$SCRIPT_DIR/lib/lang/${LANG_CHOICE}.sh"

echo -e "  ${GREEN}✓ ${LANG_CHOICE}${NC}"
echo ""

# ── Show intro ────────────────────────────────
echo -e "  $MSG_SETUP_INTRO"
echo ""

# ── Stap 1: SSH Key ──────────────────────────
echo -e "${BOLD}${MSG_SETUP_STEP1_TITLE}${NC}"
echo -e "─────────────────────────────────────────"
echo ""

SSH_KEYS=()

# Check of er keys via argument zijn meegegeven
if [[ ${#SSH_KEY_ARGS[@]} -gt 0 ]]; then
    for key in "${SSH_KEY_ARGS[@]}"; do
        if [[ "$key" =~ ^ssh-(ed25519|rsa|ecdsa)|^ecdsa-sha2 ]]; then
            SSH_KEYS+=("$key")
            echo -e "  $MSG_SETUP_KEY_VIA_ARG ${GREEN}✓${NC}"
            echo "  ${key:0:50}..."
        else
            echo -e "  ${RED}$MSG_SETUP_KEY_INVALID ${key:0:30}...${NC}"
        fi
    done
    echo ""
else
    # Zoek automatisch naar lokale SSH keys
    FOUND_KEYS=()
    KEY_FILES=()

    for keyfile in ~/.ssh/id_*.pub; do
        if [[ -f "$keyfile" ]]; then
            FOUND_KEYS+=("$(cat "$keyfile")")
            KEY_FILES+=("$keyfile")
        fi
    done

    if [[ ${#FOUND_KEYS[@]} -gt 0 ]]; then
        echo "  $MSG_SETUP_FOUND_KEYS"
        echo ""
        for i in "${!FOUND_KEYS[@]}"; do
            KEY_TYPE=$(echo "${FOUND_KEYS[$i]}" | awk '{print $1}')
            KEY_COMMENT=$(echo "${FOUND_KEYS[$i]}" | awk '{print $3}')
            echo -e "  ${GREEN}[$((i+1))]${NC} ${KEY_FILES[$i]}"
            echo "      Type: $KEY_TYPE"
            [[ -n "$KEY_COMMENT" ]] && echo "      Comment: $KEY_COMMENT"
            echo ""
        done

        echo -e "  ${GREEN}[A]${NC} $MSG_SETUP_ALL_KEYS"
        echo -e "  ${GREEN}[P]${NC} $MSG_SETUP_PASTE_KEY"
        echo -e "  ${YELLOW}[S]${NC} $MSG_SETUP_SKIP"
        echo ""
        read -rp "  $MSG_SETUP_KEY_CHOICE_PROMPT" KEY_CHOICE
        KEY_CHOICE=${KEY_CHOICE:-1}

        case $KEY_CHOICE in
            [Aa])
                for i in "${!FOUND_KEYS[@]}"; do
                    SSH_KEYS+=("${FOUND_KEYS[$i]}")
                done
                echo -e "  ${GREEN}✓${NC} $MSG_SETUP_ALL_SELECTED"
                ;;
            [Pp])
                echo ""
                echo "  $MSG_SETUP_PASTE_PROMPT"
                echo "  $MSG_SETUP_PASTE_HINT"
                echo ""
                read -r PASTED_KEY
                [[ -n "$PASTED_KEY" ]] && SSH_KEYS+=("$PASTED_KEY")
                ;;
            [Ss])
                echo -e "  ${YELLOW}$MSG_SETUP_SKIP_NOTE${NC}"
                ;;
            *)
                # Verwerk komma-gescheiden nummers (bijv. "1,2" of enkel "1")
                IFS=',' read -ra SELECTIONS <<< "$KEY_CHOICE"
                for sel in "${SELECTIONS[@]}"; do
                    sel=$(echo "$sel" | tr -d ' ')
                    if [[ "$sel" =~ ^[0-9]+$ ]]; then
                        IDX=$((sel - 1))
                        if [[ $IDX -ge 0 && $IDX -lt ${#FOUND_KEYS[@]} ]]; then
                            SSH_KEYS+=("${FOUND_KEYS[$IDX]}")
                            echo -e "  ${GREEN}✓${NC} $MSG_SETUP_KEY_SELECTED ${KEY_FILES[$IDX]}"
                        else
                            echo -e "  ${RED}$MSG_SETUP_INVALID_CHOICE $sel${NC}"
                        fi
                    fi
                done
                ;;
        esac
    else
        echo "  $MSG_SETUP_NO_KEYS_FOUND"
        echo ""
        echo "  $MSG_SETUP_CAN_DO"
        echo -e "  ${GREEN}[P]${NC} $MSG_SETUP_PASTE_A_KEY"
        echo -e "  ${GREEN}[G]${NC} $MSG_SETUP_GENERATE_KEY"
        echo -e "  ${YELLOW}[S]${NC} $MSG_SETUP_SKIP"
        echo ""
        read -rp "  $MSG_SETUP_CHOICE [P]: " KEY_CHOICE
        KEY_CHOICE=${KEY_CHOICE:-P}

        case $KEY_CHOICE in
            [Pp])
                echo ""
                echo "  $MSG_SETUP_PASTE_PROMPT"
                read -r PASTED_KEY
                [[ -n "$PASTED_KEY" ]] && SSH_KEYS+=("$PASTED_KEY")
                ;;
            [Gg])
                echo ""
                read -rp "  $MSG_SETUP_KEY_COMMENT_PROMPT [$(whoami)@$(hostname)]: " KEY_COMMENT
                KEY_COMMENT=${KEY_COMMENT:-"$(whoami)@$(hostname)"}
                ssh-keygen -t ed25519 -C "$KEY_COMMENT" -f ~/.ssh/id_ed25519 -N ""
                SSH_KEYS+=("$(cat ~/.ssh/id_ed25519.pub)")
                echo ""
                echo -e "  ${GREEN}✓${NC} $MSG_SETUP_KEY_GENERATED"
                echo ""
                echo -e "  ${YELLOW}$MSG_SETUP_KEY_REMINDER${NC}"
                ;;
            [Ss])
                echo -e "  ${YELLOW}$MSG_SETUP_SKIPPED${NC}"
                ;;
        esac
    fi
fi

# Validatie en installatie SSH keys
if [[ ${#SSH_KEYS[@]} -gt 0 ]]; then
    VALID_KEYS=()
    for key in "${SSH_KEYS[@]}"; do
        if [[ "$key" =~ ^ssh-(ed25519|rsa|ecdsa)|^ecdsa-sha2 ]]; then
            VALID_KEYS+=("$key")
        else
            echo -e "  ${RED}$MSG_SETUP_KEY_INVALID_SKIP ${key:0:30}...${NC}"
        fi
    done

    if [[ ${#VALID_KEYS[@]} -gt 0 ]]; then
        # Bouw YAML-regels: eerste key vervangt placeholder, extra keys worden toegevoegd
        FIRST_KEY="${VALID_KEYS[0]}"
        for file in "$SCRIPT_DIR"/snippets/*.yaml; do
            # Vervang placeholder met eerste key
            sed -i "s|YOUR_SSH_PUBLIC_KEY_HERE|$FIRST_KEY|g" "$file"
            # Voeg extra keys toe na de eerste key regel
            for ((i=1; i<${#VALID_KEYS[@]}; i++)); do
                sed -i "/$(echo "$FIRST_KEY" | head -c 40)/a\\      - ${VALID_KEYS[$i]}" "$file"
            done
        done
        echo -e "  ${GREEN}✓ $MSG_SETUP_KEYS_SET${NC}"
    else
        echo -e "  ${RED}$MSG_SETUP_NO_VALID_KEYS${NC}"
        echo -e "  ${YELLOW}$MSG_SETUP_PLACEHOLDER_STAYS${NC}"
    fi
fi

echo ""

# ── Stap 2: Deploy Key (optioneel) ──────────
echo -e "${BOLD}${MSG_SETUP_STEP2_DEPLOY_TITLE:-Step 2/4: Deploy Key (optional)}${NC}"
echo -e "─────────────────────────────────────────"
echo ""
echo -e "  $MSG_SETUP_DEPLOY_DESC"
echo ""
echo -e "  ${GREEN}[P]${NC} $MSG_SETUP_DEPLOY_PASTE"
echo -e "  ${YELLOW}[S]${NC} $MSG_SETUP_DEPLOY_SKIP"
echo ""
read -rp "  $MSG_SETUP_CHOICE [S]: " DEPLOY_CHOICE
DEPLOY_CHOICE=${DEPLOY_CHOICE:-S}

DEPLOY_KEY=""

# Detecteer of de gebruiker direct een SSH key heeft geplakt
if [[ "$DEPLOY_CHOICE" =~ ^ssh-(ed25519|rsa|ecdsa)|^ecdsa-sha2 ]]; then
    DEPLOY_KEY="$DEPLOY_CHOICE"
elif [[ "$DEPLOY_CHOICE" == [Pp] ]]; then
    echo ""
    echo "  $MSG_SETUP_DEPLOY_PASTE_PROMPT"
    echo "  $MSG_SETUP_PASTE_HINT"
    echo ""
    read -r DEPLOY_KEY
elif [[ "$DEPLOY_CHOICE" != [Ss] && -n "$DEPLOY_CHOICE" ]]; then
    echo -e "  ${YELLOW}$MSG_SETUP_SKIPPED${NC}"
fi

if [[ -n "$DEPLOY_KEY" ]]; then
    if [[ "$DEPLOY_KEY" =~ ^ssh-(ed25519|rsa|ecdsa)|^ecdsa-sha2 ]]; then
        # Vervang deploy key placeholder in alle snippets (→ root authorized_keys)
        for file in "$SCRIPT_DIR"/snippets/*.yaml; do
            sed -i "s|DEPLOY_SSH_PUBLIC_KEY_HERE|$DEPLOY_KEY|g" "$file"
        done
        echo -e "  ${GREEN}✓ $MSG_SETUP_DEPLOY_SET${NC}"
    else
        echo -e "  ${RED}$MSG_SETUP_KEY_INVALID_SKIP ${DEPLOY_KEY:0:30}...${NC}"
        DEPLOY_KEY=""
    fi
else
    echo -e "  ${YELLOW}$MSG_SETUP_SKIPPED${NC}"
fi

echo ""

# ── Stap 3: Template ID ──────────────────────
echo -e "${BOLD}${MSG_SETUP_STEP3_TPL_TITLE:-Step 3/4: Proxmox Template}${NC}"
echo -e "─────────────────────────────────────────"
echo ""

# Toon beschikbare templates als we op Proxmox draaien
TPL_FOUND=false
if command -v qm &>/dev/null; then
    TPL_LIST=$(qm list 2>/dev/null | tail -n +2 | while read -r line; do
        VMID=$(echo "$line" | awk '{print $1}')
        IS_TPL=$(qm config "$VMID" 2>/dev/null | grep "^template:" | awk '{print $2}')
        if [[ "$IS_TPL" == "1" ]]; then
            NAME=$(qm config "$VMID" 2>/dev/null | grep "^name:" | awk '{print $2}')
            echo "    [$VMID] $NAME"
        fi
    done)

    if [[ -n "$TPL_LIST" ]]; then
        echo "  $MSG_SETUP_AVAILABLE_TEMPLATES"
        echo "$TPL_LIST"
        echo ""
        echo -e "  ${GREEN}✓ $MSG_SETUP_TPL_READY${NC}"
        TPL_FOUND=true
    fi
fi

if [[ "$TPL_FOUND" != true ]]; then
    echo -e "  ${YELLOW}$MSG_SETUP_TPL_NONE_FOUND${NC}"
    echo -e "  $MSG_SETUP_TPL_CREATE_HINT"
fi

echo ""

# ── Stap 4: Storage ──────────────────────────
echo -e "${BOLD}${MSG_SETUP_STEP4_TITLE:-Step 4/4: Storage}${NC}"
echo -e "─────────────────────────────────────────"
echo ""

# Probeer beschikbare storage te vinden
if command -v pvesm &>/dev/null; then
    echo "  $MSG_SETUP_AVAILABLE_STORAGE"
    pvesm status 2>/dev/null | tail -n +2 | awk '{printf "    [%s] type: %s\n", $1, $2}'
    echo ""
fi

VM_STORAGE_DEFAULT="${EXISTING_VM_STORAGE:-local-lvm}"
read -rp "  ${MSG_SETUP_STORAGE_VM_PROMPT:-Storage for VM disks} [${VM_STORAGE_DEFAULT}]: " VM_STORAGE_IN
VM_STORAGE="${VM_STORAGE_IN:-$VM_STORAGE_DEFAULT}"

LXC_STORAGE_DEFAULT="${EXISTING_LXC_STORAGE:-$VM_STORAGE}"
read -rp "  ${MSG_SETUP_STORAGE_LXC_PROMPT:-Storage for LXC rootfs} [${LXC_STORAGE_DEFAULT}]: " LXC_STORAGE_IN
LXC_STORAGE="${LXC_STORAGE_IN:-$LXC_STORAGE_DEFAULT}"

LXC_TPL_DEFAULT="${EXISTING_LXC_TEMPLATE_STORAGE:-local}"
read -rp "  ${MSG_SETUP_STORAGE_LXC_TPL_PROMPT:-Storage for LXC templates} [${LXC_TPL_DEFAULT}]: " LXC_TPL_IN
LXC_TEMPLATE_STORAGE="${LXC_TPL_IN:-$LXC_TPL_DEFAULT}"

# Persist all storage keys to lib/config.sh (single source of truth)
{
    echo "VM_STORAGE=\"$VM_STORAGE\""
    echo "LXC_STORAGE=\"$LXC_STORAGE\""
    echo "LXC_TEMPLATE_STORAGE=\"$LXC_TEMPLATE_STORAGE\""
} >> "$SCRIPT_DIR/lib/config.sh"

# Backwards compat: also sync into create-vm.sh's STORAGE= line
sed -i "s|^STORAGE=.*|STORAGE=\"$VM_STORAGE\"|" "$SCRIPT_DIR/scripts/create-vm.sh"

echo -e "  ${GREEN}✓ $MSG_SETUP_STORAGE_SET VM=$VM_STORAGE, LXC=$LXC_STORAGE, templates=$LXC_TEMPLATE_STORAGE${NC}"
echo ""

# ── Samenvatting ──────────────────────────────
echo -e "${GREEN}╔════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  ${MSG_SETUP_COMPLETE_HEADER}                        ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════╝${NC}"
echo ""
echo "  $MSG_SETUP_CONFIG"
if [[ ${#SSH_KEYS[@]} -gt 0 ]]; then
    echo -e "    SSH Keys:    ${GREEN}${#VALID_KEYS[@]} $MSG_SETUP_SSH_KEYS_SET${NC}"
else
    echo -e "    SSH Keys:    ${YELLOW}$MSG_SETUP_SSH_KEYS_NOT_SET${NC}"
fi
if [[ -n "$DEPLOY_KEY" ]]; then
    echo -e "    Deploy Key:  ${GREEN}$MSG_SETUP_DEPLOY_SUMMARY_SET${NC}"
else
    echo -e "    Deploy Key:  ${YELLOW}$MSG_SETUP_DEPLOY_SUMMARY_NONE${NC}"
fi
echo "    VM storage:  $VM_STORAGE"
echo "    LXC storage: $LXC_STORAGE"
echo "    LXC tpl:     $LXC_TEMPLATE_STORAGE"
echo ""
echo "  $MSG_SETUP_NEXT_STEP"
echo ""
echo -e "    ${BOLD}bash install.sh${NC}"
echo ""
echo "  $MSG_SETUP_NEXT_STEP_DESC1"
echo "  $MSG_SETUP_NEXT_STEP_DESC2"
echo ""
